/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login.store": [],
    "logout": [],
    "register.store": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "main": [],
    "about_us": [],
    "feedback.index": [],
    "vakancies.index": [],
    "login": [],
    "register": [],
    "feedback.store": [],
    "order.store": [],
    "order.update": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "order.indexMobile": [],
    "order.destroy": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "order.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "home": [],
    "admin": [],
    "XMLExport": [],
    "feedback.destroy": [
        {
            "name": "feedback",
            "required": true,
            "binding": "id"
        }
    ],
    "news.index": [],
    "news.indexMobile": [],
    "news.create": [],
    "news.edit": [
        {
            "name": "news",
            "required": true,
            "binding": "id"
        }
    ],
    "news.update": [
        {
            "name": "news",
            "required": true,
            "binding": "id"
        }
    ],
    "news.store": [],
    "news.destroy": [
        {
            "name": "news",
            "required": true,
            "binding": "id"
        }
    ],
    "user.index": [],
    "user.indexMobile": [],
    "user.store": [],
    "user.create": [],
    "user.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.ban": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.unban": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "vacancy.index": [],
    "vacancy.management": [],
    "vacancy.store": [],
    "vacancy.edit": [
        {
            "name": "vacancy",
            "required": true,
            "binding": "id"
        }
    ],
    "vacancy.create": [],
    "vacancy.destroy": [
        {
            "name": "vacancy",
            "required": true,
            "binding": "id"
        }
    ],
    "vacancy.update": [
        {
            "name": "vacancy",
            "required": true,
            "binding": "id"
        }
    ],
    "vacancy.restore": [
        {
            "name": "vacancy",
            "required": true
        }
    ],
    "vacancy.destroyed": [],
    "vacancy.show": [
        {
            "name": "vacancy",
            "required": true,
            "binding": "id"
        }
    ],
    "flying.index": [],
    "flying.create": [],
    "flying.store": [],
    "flying.show": [
        {
            "name": "flying",
            "required": true,
            "binding": "id"
        }
    ],
    "flying.edit": [
        {
            "name": "flying",
            "required": true,
            "binding": "id"
        }
    ],
    "flying.update": [
        {
            "name": "flying",
            "required": true,
            "binding": "id"
        }
    ],
    "flying.destroy": [
        {
            "name": "flying",
            "required": true,
            "binding": "id"
        }
    ],
    "otclice.index": [],
    "otclice.create": [
        {
            "name": "vacancy",
            "required": true,
            "binding": "id"
        }
    ],
    "otclice.store": [],
    "otclice.destroy": [
        {
            "name": "otclice",
            "required": true,
            "binding": "id"
        }
    ],
    "otclice.update": [
        {
            "name": "otclice",
            "required": true,
            "binding": "id"
        }
    ],
    "news.show": [
        {
            "name": "news",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
